config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create,:show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, class_name: "Flight", foreign_key: :arrival_airport_id
  has_many :departing_flights, class_name: "Flight", foreign_key: :departure_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passangers, class_name: "User", dependent: :destroy

  accepts_nested_attributes_for :passangers

  validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_many :bookings
  has_many :passangers, through: :bookings


  def self.search(flight_params)
      departure_airport = Airport.find_by(airport_code: flight_params[:departure_code])
      arrival_airport = Airport.find_by(airport_code: flight_params[:arrival_code])
      start_date = flight_params[:flight_date]
      self.where(departure_airport_id: departure_airport.id).where(arrival_airport_id: arrival_airport.id).where(flight_date: start_date)     
  end

  def departure_code
    departure_airport.airport_code
  end

  def arrival_code
    arrival_airport.airport_code
  end

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :booking

  validates :username, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new(flight: @flight)
    params[:num_tickets].to_i.times{@booking.passangers.build}
  end

  def create
    @booking = Booking.new(booking_params)
    @flight = @booking.flight
    if @booking.save
      redirect_to @booking, notice: "Booking successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end


  private
  def booking_params
    params.require(:booking).permit(:flight_id, passangers_attributes: [:username, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    if params[:flight].nil?
      @flights = []
    else
      @flights = Flight.search(flight_params)
    end
  end

  def flight_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :flight_date,:flight_duration,:flight, :departure_code, :arrival_code, :passangers)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h2> Booking Flight to  <%= @flight.arrival_airport.airport_code%> </h2>

<p>
    From <%= @flight.departure_airport.airport_code %> to <%= @flight.arrival_airport.airport_code %><br>
    Departure: <%= @flight.flight_date.strftime("%B %d, %Y %I:%M %p") %><br>
    Duration: <%= @flight.flight_duration %> minutes
</p>

<%= form_with model: @booking, url: bookings_path, local: true do |booking_form| %>
    <%= booking_form.hidden_field :flight_id, values: @flight.id%>

    <h3> Passanger Details </h3>
    <%= booking_form.fields_for :passangers do |passanger_details|%>
        <div>
            <%= passanger_details.label :username, "Full Name" %>
            <%= passanger_details.text_field :username %>

            <%= passanger_details.label :email, "Email" %>
            <%= passanger_details.text_field :email%>
        </div>
    <%end%>

    <%= booking_form.submit "Book Flight" %>
<%end%>

app/views/bookings/show.html.erb
<h2>Booking Confirmation</h2>

<p>
  You have booked the following flight:<br>
  From <%= @booking.flight.departure_airport.airport_code %> to <%= @booking.flight.arrival_airport.airport_code %><br>
  Departure: <%= @booking.flight.flight_date.strftime("%B %d, %Y %I:%M %p") %><br>
  Duration: <%= @booking.flight.flight_duration %> minutes
</p>

<h3>Passenger Information</h3>
<ul>
  <% @booking.passangers.each do |passanger| %>
    <li><%= passanger.username %> (<%= passanger.email %>)</li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<h1>Flights On The Go !</h1>

<h5> Search </h5>

<%= form_with url: flights_path , method: :get, local: true do |flight_form|%>
    <%=collection_select(:flight, :departure_code, Flight.all, :departure_code, :departure_code, prompt: false)%>
    <%=collection_select(:flight, :arrival_code, Flight.all, :arrival_code, :arrival_code, prompt: false)%>
    <%=collection_select(:flight, :flight_date, Flight.all, :flight_date, :flight_date, prompt: false)%>

    <div>
        <%= label_tag :passengers, "Number of Passengers" %>
        <%= select_tag :passangers, options_for_select(1..4, params[:passangers]) %>
    </div>


    <%= flight_form.submit "Flight Search", name: nil%>

<%end%>

<% if @flights.any? %>
  <h2>Available Flights</h2>
  <%= form_with url: new_booking_path, method: :get, local: true do %>
    <%= hidden_field_tag :num_tickets, params[:passangers] %>
    <ul>
      <% @flights.each do |flight| %>
        <li>
          <%= radio_button_tag :flight_id, flight.id %>
          <%= flight.departure_airport.airport_code %> to <%= flight.arrival_airport.airport_code %> |
          Departure: <%= flight.flight_date.strftime("%B %d, %Y %I:%M %p") %> |
          Duration: <%= flight.flight_duration %> minutes
        </li>
      <% end %>
    </ul>
    <%= submit_tag "Choose Flight" %>
  <% end %>
<% else %>
  <p>No flights found for your search criteria.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>